### ISSUE TITLE
Logging Validator not working

### ISSUE THREAD

**Issue by notoriousturtle** [airlift/airlift#1022]
I'm trying to implement `LoggingConfiguration`. I noticed the validators aren't being called.

Below is my example code:
```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public String configLog()
    {
        final Logger log;
        final LoggingConfiguration lc;

        log = Logger.get(ServiceModule.class);

        lc = new LoggingConfiguration();
        lc.setCompression(null);

        log.info("%s", lc.getCompression());

        return "ok";
    }
```

Validator usage for `getCompression()`:
https://github.com/airlift/airlift/blob/fd85d8282658e758cd79cbcc6a1890bd7c947d73/log-manager/src/main/java/io/airlift/log/LoggingConfiguration.java#L96

This should cause an error right? Since compression is set to null.

**Comment by findepi** [comment]
These annotations are not part of JLS and are not enforced by Java runtime directly.
They are used by "bean validation".
