### ISSUE TITLE
HTTP client's UnexpectedResponseException can log sensitive info 

### ISSUE THREAD

**Issue by Laonel** [airlift/airlift#1049]
`io.airlift.http.client.UnexpectedResponseException` overrides `toString()` and adds to it`io.airlift.http.client.Request` object. This logs the entire request object, including headers, when `UnexpectedResponseException` is thrown, and can potentially leak sensitive information, like authorization header value.

Is it worth limiting the data returned by the exception's `toString()` method, maybe hiding the request headers?

**Comment by electrum** [comment]
Yeah, that seems like a good idea. I think the request method and URI is sufficient.

**Comment by Laonel** [comment]
Thanks @electrum, I've prepared a PR with a fix https://github.com/airlift/airlift/pull/1050.
