### ISSUE TITLE
airlift-server versions using Jetty > 12.0.11 do not call `ContainerResponseFilter` when an exception is raised

### ISSUE THREAD

**Issue by mosiac1** [airlift/airlift#1275]
## Summary 

With `airlift-server` > `252`, a bound `ContainerResponseFilter` implementation will not get called if a `RuntimeException` is raised in a Resource while processing the request.

## Details

This issue was originally found in https://github.com/trinodb/aws-proxy/pull/156.

Airlift version `253` upgraded the Jetty version 12.0.12.

I created a https://github.com/mosiac1/airlift-example as a minimal example an to make sure the issue is not related to `aws-proxy`.

## Steps to reproduce:

1. Clone https://github.com/mosiac1/airlift-example;
2. Run `mvn clean package`, the tests should fail;
3. Update `dep.airlift.version` to `252` in `pom.xml`;
4. Run `mvn clean package`, the tests should pass.

## Environment 

```
> java --version
openjdk 22 2024-03-19
OpenJDK Runtime Environment Temurin-22+36 (build 22+36)
OpenJDK 64-Bit Server VM Temurin-22+36 (build 22+36, mixed mode)

> mvn --verison
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /Users/mosiac/.sdkman/candidates/maven/current
Java version: 22, vendor: Eclipse Adoptium, runtime: /Users/mosiac/.sdkman/candidates/java/22-tem
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "14.7", arch: "aarch64", family: "mac"
```

**Comment by mosiac1** [comment]
The `ContainerResponseFilter` is called correctly  if a `ExceptionMapper` is registered and processes the exceptions thrown in Resources.

**Comment by mosiac1** [comment]
@wendigo Based on the maintainer call this was intentionally done to support HTTP/2. Can we close the issue? Should this be mentioned in release notes?

**Comment by wendigo** [comment]
@mosiac1: https://github.com/eclipse-ee4j/jersey/blob/2fd3e28a206f02a4d31331092fd6546d6d4d770f/core-server/src/main/java/org/glassfish/jersey/server/ServerProperties.java#L636, this is now set to true
