### ISSUE TITLE
Deprecate or remove io.airlift.testing.Assertions

### ISSUE THREAD

**Issue by ebyhr** [airlift/airlift#1303]
At least Trino replaced the class with AssertJ. https://github.com/trinodb/trino/pull/23844

**Comment by ebyhr** [comment]
cc: @wendigo

**Comment by wendigo** [comment]
@ebyhr Can you open a PR that removes these assertions? There is no point in keeping them here - this will force downstream projects to switch to AssertJ

**Comment by ebyhr** [comment]
@wendigo https://github.com/airlift/airlift/pull/1304
