### ISSUE TITLE
Airlift HyperLogLog cardinality estimates over the same data can have large variance

### ISSUE THREAD

**Issue by erichwang** [airlift/airlift#261]
Given an input data set of about 5 million unique numbers, if you randomly shuffle the values and add them in chunks of 24k to different hyperloglogs and then merge them together, the cardinality estimate can vary by as much as 0.1% to 0.3%. This variability gets much worse the more buckets you use in the hyperloglogs.

Two observations:
- Forcing all hyperloglogs to start off as dense does not have this problem.
- Using a single hyperloglog over this whole data set does not have this problem (no merging).

Test program:
http://pastebin.com/zm5ZHswK

**Comment by electrum** [comment]
This should be fixed by the new format.
