### ISSUE TITLE
Contribute overridden Jetty classes back to jetty project

### ISSUE THREAD

**Issue by gregw** [airlift/airlift#274]
I've just noticed the airlift project overrides several jetty classes - like schedulers and threadpool, to do such stuff like support thread groups.

The Jetty project would be more than pleased to update our classes to support things like thread groups.   So when you need stuff like that, please ask on https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Jetty and we shall probably deliver.  Better yet, just give us a pull request against https://github.com/eclipse/jetty.project

cheers

**Comment by johngmyers** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=462098

**Comment by gregw** [comment]
thanks for the contributions.  merged and will be in jetty-9.3.0.    I'm sure this will give you a bit of a version nightmare... but eventually it will be good
