### ISSUE TITLE
Presto UI broken as a result of replacing GzipFilter with GzipHandler

### ISSUE THREAD

**Issue by petroav** [airlift/airlift#391]
We've been using a SNAPSHOT version of Airlift internally because we need a Kerberos fix (https://github.com/airlift/airlift/commit/932d490e67c97ca24ee0240097bdcafac57f66bb) that isn't part of any release. With this SNAPSHOT version we noticed that the Presto UI was "broken". See the attached screenshot for a concrete example on what I mean by "broken". Running queries doesn't change anything, it remains this way. We tried a couple of different browsers and a couple of different installations.

The Airlift 0.124 release does not break the UI. I tried three different versions of Airlift, each excluding a different commit since the 0.124 release and narrowed the culprit down to the last commit (https://github.com/airlift/airlift/commit/218bbfe5bb1b90235c1f9cc00b9d85c16f97e326). I don't understand how that commit can break the UI, which is why I'm not putting a PR along with this. If it's a relatively simple fix, let me know and I'd be happy to provide a patch.

![prestoui](https://cloud.githubusercontent.com/assets/665991/13681599/ef3d1b3c-e6cb-11e5-9aee-6a367df6aff4.png)

**Comment by martint** [comment]
It seems to be corrupting the output for some of the static resources. I'll take a look.

**Comment by raghavsethi** [comment]
@martint We really need to release because there's additional instrumentation needed to debug an ongoing problem. Could you tale a look soon or give me some additional context so that I can fix this?

**Comment by petroav** [comment]
@raghavsethi thanks for fixing this. Feel free to close the issue (I can't seem to be able to close it myself).

**Comment by martint** [comment]
Fixed
