### ISSUE TITLE
There's no documentation.

### ISSUE THREAD

**Issue by Titousensei** [airlift/airlift#417]
Some general description and examples would really be appreciated.

**Comment by BigDataDaddy** [comment]
+1

**Comment by narramadan** [comment]
+1

**Comment by javeria2** [comment]
+1

**Comment by hustwolf** [comment]
+1

**Comment by renannprado** [comment]
Is there any documentation whatsoever or all that is available is just javadocs?

**Comment by findepi** [comment]
There is no separate project documentation and we currently have no plans to create one.
However, you can ask any Airlift-related questions on the `#airlift` channel on [Presto slack](https://prestosql.io/slack.html).

**Comment by findepi** [comment]
Closed by https://github.com/airlift/airlift/pull/916
