### ISSUE TITLE
TestMoreFutures.testTimeout() failures due to race

### ISSUE THREAD

**Issue by johngmyers** [airlift/airlift#447]
The assertion

`assertTrue(rootFuture.isDone());`

intermittently fails because `TimeoutFutureTask.run()` completes `timeoutFuture` before canceling `rootFuture`. The assertion can run and fail before rootFuture is canceled.

@dain should it be a requirement that the rootFuture be canceled before the timeoutFuture is completed?

**Comment by dain** [comment]
@johngmyers I don't think we can cancel the `rootFuture` before the `timoutFuture` is completed because the root completion would race with the timout.
