### ISSUE TITLE
Incorrect dependency on "jackson-datatype-jdk7" version "2.7.4"

### ISSUE THREAD

**Issue by abhimaloo** [airlift/airlift#497]
Looks like "io.airlift-json" and "io.airlift-http-client" artifacts looks for **"jackson-datatype-jdk7"** library when you give <dep.jackson.version>**2.7.4**</dep.jackson.version>. 

jackson's **2.7.4** version does not contain "jackson-datatype-jdk7" library. I tried excluding this from the dependencies but it broke one of my unit test with this exception - 

Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/datatype/jdk7/Jdk7Module
[ERROR] at io.airlift.json.ObjectMapperProvider.<init>(ObjectMapperProvider.java:56)
[ERROR] at io.airlift.json.JsonCodec$1.get(JsonCodec.java:39)
[ERROR] at io.airlift.json.JsonCodec$1.get(JsonCodec.java:36)
[ERROR] at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
[ERROR] at io.airlift.json.JsonCodec.listJsonCodec(JsonCodec.java:65)
[ERROR] at com.facebook.puma.router.TestServer.<clinit>(TestServer.java:82)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[ERROR] at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
[ERROR] at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:387)
[ERROR] ... 23 more
[ERROR] Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.datatype.jdk7.Jdk7Module
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by electrum** [comment]
Please update to Airlift 0.135+ (latest is recommended), which updates to Jackson 2.8 and removes the dependency on the now-defunct `jackson-datatype-jdk7` module.
