### ISSUE TITLE
Deployment exception

### ISSUE THREAD

**Issue by akyekth** [airlift/airlift#522]
Hi trying to deploy project in glassfish 4.1.1 i got the below exception.Using Presto 0.145

Payara 4.1|javax.enterprise.system.core|_ThreadID=94;_ThreadName=admin-thread-pool(6);_TimeMillis=1493383149301;_LevelValue=1000;|Exception while deploying the app [hopsworks-api] : The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]
The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:375)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:383)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.processAnnotations(AnnotationProcessor

If anyone got this exception, please help me.

Thanks in Advance
Aruna

**Comment by dain** [comment]
It seems like glassfish has extra restrictions on `@PreDestroy` that we do not have.  I don't think this is something we are likely to change.  Maybe you can check if there is a way to disable this annotation scanning in Glassfish.
