### ISSUE TITLE
Implement filter using airlift ?

### ISSUE THREAD

**Issue by dabansal** [airlift/airlift#554]
Hi,

I want to implement a filter  in one of our projects which is using airlift.

httpServerBinder(binder).bindResource("/", "webapp").withWelcomeFile("index.html");

Above line is what we are using to map the url with the a static resource . Can someone help with sample code which I can write to intercept request to "/" so I can authenticate the call.

Thanks,
Dheeraj

**Comment by electrum** [comment]
Sorry for the long delay in replying. You can bind a `javax.servlet.Filter` like this:
```java
Multibinder.newSetBinder(binder, Filter.class, TheServlet.class)
        .addBinding().to(CustomFilter.class).in(Scopes.SINGLETON);

**Comment by electrum** [comment]
A real example: https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/security/ServerSecurityModule.java
