### ISSUE TITLE
Launcher does not support start in foreground 

### ISSUE THREAD

**Issue by nishantrayan** [airlift/airlift#657]
With presto we have `launcher run` for debugging and `launcher start` that forks to the background. This creates a particular problem with tools like [runit](http://smarden.org/runit/faq.html#create) which requires the process to run in foreground. It will be great if launcher supports something like `launcher start-fg` that creates a thread and not fork to a complete background process

**Comment by electrum** [comment]
How is this different than the “run” command? That’s exactly what it’s designed for.

**Comment by nishantrayan** [comment]
@electrum I may lack some understanding here. with run the logs tend to go to stdout and does log gc and other stats which felt a little limiting. is there a way to add options in run to do that ?

**Comment by electrum** [comment]
Tools like runit expect logs to go to stdout/stderr. Make sure you capture both.

If you want to log GC, you need to add JVM flags to do so.

**Comment by nishantrayan** [comment]
let me check out way to log gc to separate file. We also want to do this production . We see that run should be used for debugging only https://github.com/airlift/airlift/blob/master/launcher/src/main/scripts/bin/launcher#L29 are there any known pitfalls ?

**Comment by electrum** [comment]
We use “run” for all of our production clusters (using a tool that works like runit).

**Comment by nishantrayan** [comment]
thanks @electrum that is reassuring ..  closing this issue as resolved.
