### ISSUE TITLE
Can we bring back the pre-check for existing jmx agent in JmxAgent9?

### ISSUE THREAD

**Issue by zhenyuy-fb** [airlift/airlift#672]
JmxAgent9 removed the pre-checking for the JmxAgent status before starting it's own, which is different from JmxAgent8. This means if the agent has already started via command line properties passed to the jvm, JmxAgent9 will run into this exception when calling: virtualMachine.startManagementAgent(properties), which tends to cause confusion unnecessary.

**Comment by electrum** [comment]
This should be fixed by https://github.com/airlift/airlift/pull/733
