### ISSUE TITLE
How to compile a jar file

### ISSUE THREAD

**Issue by akki700** [airlift/airlift#793]
Hey Folks,

I am new to Airlift and I was going through the framework and it seems that it would work for an application that I am working to be hosted as a web app. Unfortunately after going through the code and the sample server files, I am still not sure how to go about building it and compiling it to create a JAR file. Can someone help?

**Comment by findepi** [comment]
@akki700 airlift-based app is typically built into a .tar.gz file with a launcher script included inside.

to achieve this you need:

* `.build-airlift` empty file in the base of your app 
* using airbase as the parent project:

```
   <parent>
        <groupId>io.airlift</groupId>
        <artifactId>airbase</artifactId>
        <version>93</version>
    </parent>
```

see https://github.com/prestosql/presto/tree/master/presto-proxy for example

the most activey Airlift userbase is Presto community.
Join the Presto slack https://prestosql.io/slack.html > #dev channel if you have further questions
