### ISSUE TITLE
log config max-history of http client not work

### ISSUE THREAD

**Issue by gjhkael** [airlift/airlift#894]
My config is below, max history set to exchange http client log.
```
#exchange
exchange.http-client.log.enabled=true
exchange.http-client.log.max-size=100MB
exchange.http-client.log.max-history=2
exchange.http-client.log.compression.enabled=false
```
But the old log file is not deleted.
![image](https://user-images.githubusercontent.com/10809317/108977014-15b7cf00-76c3-11eb-8e39-df30a4ceda16.png)

**Comment by gjhkael** [comment]
@findepi Please review it, thanks.

**Comment by findepi** [comment]
Fixed by https://github.com/airlift/airlift/pull/896
