### ISSUE TITLE
Http-Client: BodyGeneratorContentProvider is leaking threads

### ISSUE THREAD

**Issue by mosiac1** [airlift/airlift#983]
# observed behavior

I am using airlift through Trino and working with the HTTP event listener.

This plugin creates requests for the airlift HTTP client like this:

```java
        Request request = preparePost()
                .addHeaders(Multimaps.forMap(config.getHttpHeaders()))
                .addHeader(CONTENT_TYPE, JSON_UTF_8.toString())
                .setUri(ingestUri)
                .setBodyGenerator(out -> objectWriter.writeValue(out, event))
                .build();
```

The important part there is the body generator, which creates a Body generator from a jackson ObjectWriter - this will write out the object value in multiple steps. This gets wrapped in a BodyGeneratorContentProvider [here](https://github.com/airlift/airlift/blob/2920a40f6e3452bd60e16e0a9f19a6eb83cdd3a2/http-client/src/main/java/io/airlift/http/client/jetty/JettyHttpClient.java#L649).

Because of how BodyGeneratorContentProvider uses a BlockingQueue with a limited size it can happen that Jetty will stop taking chunks out of that queue while the ObjectWriter is still trying to add new chunks. This causes the thread that is running the ObjectWriter to get deadlocked, and since that thread is from the http-client thread pool that pool will eventually be exhausted and cause that client to break (causing timeout exceptions). 

# expected behavior

Threads should not end up in a deadlock. Maybe threads should be killed if the jetty request fails.

# reproducing the error

Unfortunately, I haven't been able to reproduce this bug in an enclosed environment. I came across it in production multiple times and traced it to this problem from thread dumps. ([example thread dump](https://gist.github.com/mosiac1/0c58b9b15142d44bc6561d856a19c4d2))

**Comment by electrum** [comment]
I think we should change the `BodyGenerator` interface to return `Iterator<ByteBuffer>` to match Jetty, rather than `OutputStream` which requires threads and blocking.

For the Trino issue, we should change the Trino event listener plugin to use `StaticBodyGenerator`, which should eliminate this problem entirely. Would you like to send a PR for that?

**Comment by johngmyers** [comment]
The `BodyGenerator` interface will inherently cause deadlocks, as described in the initial description.

You could look at the `DynamicBodySource` interface of proofpoint/platform.

**Comment by mosiac1** [comment]
Thanks for the replies! If this interface is known to cause deadlocks I think it should be made a lot clear.


> For the Trino issue, we should change the Trino event listener plugin to use `StaticBodyGenerator`, which should eliminate this problem entirely. Would you like to send a PR for that?

Yep, I started working on a PR for that and will publish it today/tomorrow

**Comment by electrum** [comment]
We deprecated `BodyGenerator`. If someone needs a dynamic implementation, we can figure out a suitable replacement that matches the new Jetty APIs.
